[package]
name = "xmodits"
authors = ["B0ney https://github.com/B0ney"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at htptrPatternstps://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4.3"

[workspace]
members = [
    "app_cli",
    # "app_gui"
]