[package]
name = "xmodits-lib"
authors = ["B0ney <https://github.com/B0ney>"]
description = "XMODITS core librabry"
version = "0.2.2"
edition = "2021"
repository = "https://github.com/B0ney/xmodits"
license = "MPLv2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
# libxmodits ~307KiB
# libxmodits ~491KiB # 12/10/2022
[dependencies]
byteorder = "1.4.3"
thiserror = "1.0.32"
phf = { version = "0.11.1", features = ["macros"] }

[dev-dependencies]
sha2 = "0.10.2"
rand = "0.8.5"

[workspace]
members = [
    "app/*",
    "pylib",
]

[profile.release]
strip = true
opt-level = 3       # We want to make it fast
lto = true          # Enable Link Time Optimization
codegen-units = 1   # Reduce number of codegen units to increase optimizations.
# panic = 'abort' 

[features]
thread = []
common = []

[profile.test]
opt-level = 1
