[package]
name = "xmodits-gui"
authors = ["B0ney <https://github.com/B0ney>"]
description = "XMODITS graphical application"
version = "0.11.0"
edition = "2021"
build = "build.rs"
license = "GPLv3"
repository = "https://github.com/B0ney/xmodits"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
update_check = ["updater"]
build_info = ["built"]
audio = []
wgpu = ["iced/wgpu"]

[build-dependencies]
built = { version = "0.6.1", features = ["chrono", "git2"], optional = true }

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.12"
static_vcruntime = "2.0.0"

# [dependencies.xmodits-lib]
# git = "https://github.com/B0ney/xmodits-lib.git"
# rev = "0cb0dad"
# features = ["serde"]

[dependencies.iced]
# version = "0.10.0"
git = "https://github.com/iced-rs/iced.git"
default-features = false
features = [
    "image",
    "tokio",
    "lazy",
    "advanced",
]

[dependencies.tokio]
version = "1.29.1"
features = ["sync", "fs", "io-util", "parking_lot"]

[dependencies.rfd]
version = "0.11.4"
default-features = false
features = ["xdg-portal"]

[dependencies.native-dialog]
version = "0.6.4"
features = ["windows_dpi_awareness", "windows_visual_styles"]

[dependencies]
data = { path = "data" }
updater = { path = "updater", optional = true }

anyhow = "1.0.0"
serde = { version = "1.0", features = ["derive"] }

tracing = "0.1.37"
tracing-log = "0.1.3"
tracing-subscriber = "0.3.17"

open = "5.0.0"
walkdir = "2.3.3"
rand = "0.8.5"
parking_lot = "0.12.1"
rayon = "1.7.0"
once_cell = "1.18.0"
tempfile = "3.5.0"
dirs = "5.0.0"
chrono = { version = "0.4", features = ["serde"] }

# cosmic-time = "0.1.2"
# iced_aw = "0.4.1"
# iced_gif = "0.4.0"

# [dev-dependencies]


[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["wincon"] }

[package.metadata.winres]
OriginalFilename = "XMODITS.EXE"
FileDescription = "A tool to extract samples from tracker modules. https://github.com/B0ney/xmodits/ - GPLv3"
Comments = "This software is licensed under GPLv3. You can obtain the source code here: https://github.com/B0ney/xmodits/"

[workspace]
members = ["data", "updater"]

[profile.dev]
split-debuginfo = "packed"
incremental = true

[profile.release]
strip = true
opt-level = "s"
codegen-units = 1
