[package]
name = "xmodits-common"
authors = ["B0ney - https://github.com/B0ney"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xmodits-lib = { path = "../../" }