[package]
name = "xmodits"
authors = ["B0ney <https://github.com/B0ney>"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.2.6"
xmodits-lib = {path = "../"}

[profile.release]
# strip = true
opt-level = "z"
lto = true          # Enable Link Time Optimization
codegen-units = 1   # Reduce number of codegen units to increase optimizations.
# panic = 'abort'  


[target.'cfg(windows)'.build-dependencies]
winres = "0.1"
# msgbox = "0.7.0"