[package]
name = "audio_engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xmodits-lib.workspace = true
rodio = { version = "0.17", default-features = false }
