[package]
name = "update"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.20"
retry = "2.0.0"
flate2 = "1.0.0"
serde = "1.0.0"
futures = "0.3.0"

[features]
self_update = []