[package]
name = "xmodits-gui"
authors = ["B0ney <https://github.com/B0ney>"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xmodits-lib = { path = "../../" }
anyhow = "1.0.66"
serde = { version="1.0.147", features = ["derive"] }
toml = "0.5.9"
once_cell = "1.15.0"
dirs = "4.0.0"
tokio = "1.21.2"
rodio = { version = "0.16.0", default-features = false, features = ["symphonia-wav"] }
image = { version= "0.24.4", default-features = false, features = ["ico"] }
rfd = { version = "0.10.0", default-features = false, features = ["xdg-portal"] }
iced_native = {git = "https://github.com/iced-rs/iced"}
# native-dialog = { version="0.6.3", features= ["windows_dpi_awareness", "windows_visual_styles"] }
# crossbeam-channel = "0.5.6"
# # reqwest = { version = "0.11", features = ["blocking", "json"], optional=true } 
# log = "0.4.17"
# static_init = "1.0.3"
# ureq = ""
[dependencies.iced]
git = "https://github.com/iced-rs/iced"
features = [
    "glow", 
    "image", 
    # "tokio", 
    "glow_default_system_font"
]

# [features]
# updater = [
#     "reqwest"
# ]

# # Separate binary to update xmodits
# [[bin]]
# features = ["updater"]
# name = "xmodits_updater"
# path = ""
[profile.release]
strip = true
opt-level = 3       # We want to make it fast
lto = true          # Enable Link Time Optimization
codegen-units = 1   # Reduce number of codegen units to increase optimizations.
# panic = 'abort' 