[package]
name = "xmodits-gui"
authors = ["B0ney <https://github.com/B0ney>"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xmodits-lib = { path = "../../" }
native-dialog = { version="0.6.3", features= ["windows_dpi_awareness", "windows_visual_styles"] }
iced = { version = "0.4.2", features = ["glow", "svg", "canvas"] }
# iced_audio = "0.8.0"
rodio = "0.16.0"
crossbeam-channel = "0.5.6"
dirs = "4.0.0"
reqwest = { version = "0.11", features = ["blocking", "json"], optional=true } 
serde = {version="1.0.147", features = ["derive"] }
toml = "0.5.9"
anyhow = "1.0.66"
log = "0.4.17"

[features]
updater = [
    "reqwest"
]

# # Separate binary to update xmodits
# [[bin]]
# features = ["updater"]
# name = "xmodits_updater"
# path = ""