name: Build CLI Artifacts

on:
  workflow_dispatch:
  workflow_call:
  
jobs:
  build:
    name: Building ${{ matrix.build_target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build_target: [linux, windows]
        include:
        - build_target: linux
          os: ubuntu-latest
        - build_target: windows
          os: windows-latest
          
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target
          key: ${{ runner.os }}-release-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.OS }}-release-
        
      - name: Building CLI
        run: cargo build -p xmodits --release

      - name: Create ./bin directory
        run: mkdir -p bin
          
      - name: Tarball Linux CLI binary
        if: matrix.os != 'windows-latest'
        run: |
          tar -czf bin/xmodits-cli-${{ matrix.build_target }}.tar.gz -C target/release/ xmodits

      - name: Zip Windows CLI binary
        if: matrix.os == 'windows-latest'
        run: | # On Windows, add cli suffix
          mv target/release/xmodits.exe target/release/xmodits-cli.exe
          Compress-Archive target/release/xmodits-cli.exe bin/xmodits-cli-${{ matrix.build_target }}.zip

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: xmodits-cli-${{ matrix.build_target }}
          path: |
            bin/xmodits-cli-${{ matrix.build_target }}.*
