name: Publish

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-gui:
    uses: ./.github/workflows/build_gui_artifacts.yml

  release:
    name: Release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    needs: build-gui
    steps:
      - uses: actions/checkout@v3
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: bin
      - name: Create draft-release
        uses: softprops/action-gh-release@v1
        with:
          files: bin/*/xmodits-*
          draft: true
          prerelease: false
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

