name: Publish

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-gui:
    uses: ./.github/workflows/build_gui_artifacts.yml

  release:
    name: Release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    needs: build-gui
    steps:
      - uses: actions/checkout@v3
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: bin

      - name: Generate Checksum
        run: |
          ARTIFACTS="bin"
          find "$ARTIFACTS" -type f -exec sha256sum '{}' + | sed 's, .*/,  ,' > SHA256SUMS.txt

      - name: Create draft-release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bin/*/xmodits-*
            SHA256SUMS.txt
          draft: true
          prerelease: true
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}